image: node:16.11.1

before_script:
  - node -v

stages:
  - build

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - npm install
    - npm run compile
    - echo "Compile complete."

lint-job:
  stage: build
  script:
    - echo "Running ESlint..."
    - npm run lint
    - echo "Running ESlint complete."
