image: 'registry.gitlab.com/shardus/dev-container:latest_node18'

before_script:
  - node -v

stages:
  - build

build-job:
  cache:
    paths:
      - node_modules/
  stage: build
  script:
    - echo "Compiling the code..."
    - npm install --silent
    - npm run compile
    - echo "Compile complete."

lint-job:
  cache:
    paths:
      - node_modules/
  stage: build
  script:
    - echo "Running ESlint..."
    - npm install @typescript-eslint/eslint-plugin@5.48.0 --save-dev
    - npm run lint
    - echo "Running ESlint complete."
